### ISSUE TITLE
[bug] npx -y xactions-mcp: client/api/parsers.js missing

### ISSUE THREAD

**Issue by mxl** [nirholas/XActions#11]
Running:
```
npx -y xactions-mcp
```
gives output:
```
⚡ XActions MCP Server v3.1.0 — 140+ tools
   The free, open-source Twitter/X MCP server
   https://github.com/nirholas/XActions

💻 XActions MCP Server: Local mode (free)
   Using Puppeteer for browser automation
❌ Fatal error: Cannot find module '/Users/myuser/.npm/_npx/8fec1fedcd4443d9/node_modules/xactions/src/client/api/parsers.js' imported from /Users/myuser/.npm/_npx/8fec1fedcd4443d9/node_modules/xactions/src/client/api/users.js
```

**Comment by nirholas** [comment]
looking into this

**Comment by nirholas** [comment]
Thanks for reporting this. The current published package includes src/client/api/parsers.js, and a clean install succeeds. This was the same resolved packaging failure tracked in #9, so I am closing it as completed.
